### ISSUE TITLE
有问题！！

### ISSUE THREAD

**Issue by ftlh2005** [grapewheel/avvw#1]
npm run dev

[Vue warn]: Do not use built-in or reserved HTML elements as component id: header
warn @ vue.js:616
validateComponentName @ vue.js:1397
Vue.extend @ vue.js:4870
createComponent @ vue.js:4305
_createElement @ vue.js:4536
createElement @ vue.js:4474
vm._c @ vue.js:4605
render @ home.vue?c09a:8
Vue._render @ vue.js:4649
updateComponent @ vue.js:2906
get @ vue.js:3274
Watcher @ vue.js:3263
mountComponent @ vue.js:2913
Vue.$mount @ vue.js:8629
Vue.$mount @ vue.js:11034
init @ vue.js:4239
createComponent @ vue.js:5683
createElm @ vue.js:5630
createChildren @ vue.js:5758
createElm @ vue.js:5659
patch @ vue.js:6219
Vue._update @ vue.js:2785
updateComponent @ vue.js:2906
get @ vue.js:3274
Watcher @ vue.js:3263
mountComponent @ vue.js:2913
Vue.$mount @ vue.js:8629
Vue.$mount @ vue.js:11034
Vue._init @ vue.js:4739
Vue @ vue.js:4805
setTimeout @ home.html:37
setTimeout (async)
(anonymous) @ home.html:35
vue.js:616 [Vue warn]: Unknown custom element: <container> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Home> at src/pages/home.vue
       <Root>
warn @ vue.js:616
createElm @ vue.js:5643
patch @ vue.js:6180
Vue._update @ vue.js:2785
updateComponent @ vue.js:2906
get @ vue.js:3274
Watcher @ vue.js:3263
mountComponent @ vue.js:2913
Vue.$mount @ vue.js:8629
Vue.$mount @ vue.js:11034
init @ vue.js:4239
createComponent @ vue.js:5683
createElm @ vue.js:5630
createChildren @ vue.js:5758
createElm @ vue.js:5659
patch @ vue.js:6219
Vue._update @ vue.js:2785
updateComponent @ vue.js:2906
get @ vue.js:3274
Watcher @ vue.js:3263
mountComponent @ vue.js:2913
Vue.$mount @ vue.js:8629
Vue.$mount @ vue.js:11034
Vue._init @ vue.js:4739
Vue @ vue.js:4805
setTimeout @ home.html:37
setTimeout (async)
(anonymous) @ home.html:35
vue.js:616 [Vue warn]: Error in mounted hook: "ReferenceError: api is not defined"

found in

---> <Header> at src/components/header.vue
       <Home> at src/pages/home.vue
         <Root>
warn @ vue.js:616
logError @ vue.js:1837
globalHandleError @ vue.js:1832
handleError @ vue.js:1821
callHook @ vue.js:3047
insert @ vue.js:4260
invokeInsertHook @ vue.js:6051
patch @ vue.js:6268
Vue._update @ vue.js:2785
updateComponent @ vue.js:2906
get @ vue.js:3274
Watcher @ vue.js:3263
mountComponent @ vue.js:2913
Vue.$mount @ vue.js:8629
Vue.$mount @ vue.js:11034
Vue._init @ vue.js:4739
Vue @ vue.js:4805
setTimeout @ home.html:37
setTimeout (async)
(anonymous) @ home.html:35
vue.js:1841 ReferenceError: api is not defined
    at Object../src/libs/apicloud.js.u.fixStatusBar (apicloud.js:500)
    at VueComponent.mounted (header.vue:16)
    at callHook (vue.js:3045)
    at Object.insert (vue.js:4260)
    at invokeInsertHook (vue.js:6051)
    at Vue.patch [as __patch__] (vue.js:6268)
    at Vue._update (vue.js:2785)
    at Vue.updateComponent (vue.js:2906)
    at Watcher.get (vue.js:3274)
    at new Watcher (vue.js:3263)
logError @ vue.js:1841
globalHandleError @ vue.js:1832
handleError @ vue.js:1821
callHook @ vue.js:3047
insert @ vue.js:4260
invokeInsertHook @ vue.js:6051
patch @ vue.js:6268
Vue._update @ vue.js:2785
updateComponent @ vue.js:2906
get @ vue.js:3274
Watcher @ vue.js:3263
mountComponent @ vue.js:2913
Vue.$mount @ vue.js:8629
Vue.$mount @ vue.js:11034
Vue._init @ vue.js:4739
Vue @ vue.js:4805
setTimeout @ home.html:37
setTimeout (async)
(anonymous) @ home.html:35
vue.js:616 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'winHeight' of undefined"

found in

---> <Home> at src/pages/home.vue
       <Root>
warn @ vue.js:616
logError @ vue.js:1837
globalHandleError @ vue.js:1832
handleError @ vue.js:1821
callHook @ vue.js:3047
insert @ vue.js:4260
invokeInsertHook @ vue.js:6051
patch @ vue.js:6268
Vue._update @ vue.js:2785
updateComponent @ vue.js:2906
get @ vue.js:3274
Watcher @ vue.js:3263
mountComponent @ vue.js:2913
Vue.$mount @ vue.js:8629
Vue.$mount @ vue.js:11034
Vue._init @ vue.js:4739
Vue @ vue.js:4805
setTimeout @ home.html:37
setTimeout (async)
(anonymous) @ home.html:35
vue.js:1841 TypeError: Cannot read property 'winHeight' of undefined
    at VueComponent.mounted (home.vue:32)
    at callHook (vue.js:3045)
    at Object.insert (vue.js:4260)
    at invokeInsertHook (vue.js:6051)
    at Vue.patch [as __patch__] (vue.js:6268)
    at Vue._update (vue.js:2785)
    at Vue.updateComponent (vue.js:2906)
    at Watcher.get (vue.js:3274)
    at new Watcher (vue.js:3263)
    at mountComponent (vue.js:2913)

**Comment by grapewheel** [comment]
[Vue warn]: Do not use built-in or reserved HTML elements as component id: header
此处是只是vue警告，不是error，是因为用了html预留的header id，亲可以自己修改其他id即可

[Vue warn]: Error in mounted hook: "ReferenceError: api is not defined"
此处是由于在浏览器端使用apicloud的api sdk，这个可以忽略，因为本地预览不是在apicloud的app环境下，所以api是无法加载的，文档有说明，在真机上测试就正常了

 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'winHeight' of undefined"
此处也是由于api sdk没有加载原因，可忽略

**切记： 本地预览只是调整样式，要测试体验请真机，真机是不会有相关问题**
