### ISSUE TITLE
不支持自定义loader吗？

### ISSUE THREAD

**Issue by 17625693** [grapewheel/avvw#11]
今天测试在自定义loader，无法将代码同步成功。

**Comment by amnextking** [comment]
请详细描述问题，是否有提示或者log，我实测是没有问题的。

**Comment by 17625693** [comment]
> 请详细描述问题，是否有提示或者log，我实测是没有问题的。

之前的自定义loader 已经有之前 apicloud 同步过的项目，然后再使用 avvw 进行同步的时候。在电脑端操作，设备上并没有预期的同步代码框出来。

**Comment by 17625693** [comment]
> > 请详细描述问题，是否有提示或者log，我实测是没有问题的。
> 
> 之前的自定义loader 已经有之前 apicloud 同步过的项目，然后再使用 avvw 进行同步的时候。在电脑端操作，设备上并没有预期的同步代码框出来。

找到问题了，原来是因为 <widget id="AXXXXXXX" version="0.0.1"> 这里的 id 没有与之前的 id 一致，所以没有出现，设置后就可以了。感谢解答，最后希望可以实现热部署。

**Comment by grapewheel** [comment]
@17625693 已实现手机热加载
