### ISSUE TITLE
如何使用VS Code去调试远程设备中WebView呢

### ISSUE THREAD

**Issue by amnextking** [grapewheel/avvw#12]
我在[#10](https://github.com/grapewheel/avvw/issues/10#issuecomment-490758597)提到变相地实现真机实时预览的功能，然后我又在想能否通过VS Code去下断点来调试呢？
于是我找到了[Debugger for Chrome](https://github.com/mpotthoff/vscode-android-webview-debug)，基于这个插件我们可以在Chrome中调试程序，但由于没有APICloud环境，我们还是需要到真机/模拟器上去调试。
于是我又找到了一个基于Debugger for Chrome可以实现在VS Code上调试远程设备上的WebView的插件——[VS Code - Android WebView Debugging ](https://github.com/mpotthoff/vscode-android-webview-debug)。
我通过该插件确实可以附加在模拟器中的程序进行调试，HTML代码可以断下来，JS代码无法中断，且提示找不到xx.js。我看了webpack的dev配置，“devtool: 'inline-source-map',”也符合[Vue官方文档关于调试的要求](https://vue.docschina.org/v2/cookbook/debugging-in-vscode.html#%E5%9C%A8-Chrome-Devtools-%E4%B8%AD%E5%B1%95%E7%A4%BA%E6%BA%90%E4%BB%A3%E7%A0%81)。
请作者有时间的时候可以帮我看看，一起实现更好的开发体验！

**Comment by grapewheel** [comment]
好的，我也看看，一般我们编程不会用到断点，甚至连webview debugger都不会使用，只使用wifi log看输出，最简单直接粗暴的调试方式，因为开发久了，基本不需要重型开发工具来协助调试

**Comment by amnextking** [comment]
老司机开车稳嘛，前端我还是个新手需要一些东西去辅助，有劳作者了！

**Comment by grapewheel** [comment]
v1.2.0已支持手机热加载调试，原理是apploader映射本地测试服来进行调试，你可以重新测试下这个issue，我还没有时间测试，谢谢～

**Comment by grapewheel** [comment]
已经测试过，是可以断点，但由于apicloud的多页面运行机制，所以vs code不能每次都能和当前调试页面连接成功，所以有时可以，有时不行，需要手动修改Android WebView Debugging的配置文件，指向调试某个页面，例如：
```js
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "android-webview",
            "request": "attach",
            "name": "Attach to Android WebView",
            "application": "com.android.chrome",
            "webRoot": "${workspaceFolder}",
            "urlFilter": "file://dist/tab1.html"
        }
    ]
}
```
这种办法非常麻烦，所以我推荐你可以使用apicloud [touchDebugger](https://www.apicloud.com/mod_detail/14619)这个插件，自定义Apploader去尝试测试

**Comment by amnextking** [comment]
好的 谢谢推荐 之前用过Chrome Debug
