### ISSUE TITLE
如果要实现国际化，应该怎么处理？

### ISSUE THREAD

**Issue by 17625693** [grapewheel/avvw#13]
参考 vant 发现，在这里 需要 修改  page.ejs  这个文件，但是没有效果

**Comment by grapewheel** [comment]
根据[官方文档](https://youzan.github.io/vant/#/zh-CN/locale)提及，理论上也是和其他vant组件一样import使用即可，page.ejs是webpack生成页面模板，脚手架并没有对他做es6转义，所以不能用import等es6语法，推荐在每个需要国际化的vue页面中import，例如：
```vue
<script>
  import { Locale } from 'vant';
  import enUS from 'vant/lib/locale/lang/en-US';

  Locale.use('en-US', enUS);
</script>
```
如果不希望这么麻烦每个页面添加，可以考虑使用vue的mixins特性，其实国际化有很多实现方式，简单的实现方式是配置多个语言json文件，然后根据客户端语言版本装载对应json显示也行

**Comment by 17625693** [comment]
我试着尝试一下，感谢提供帮助。今天看到了支持热重载，那真是太棒了，越来越好。

**Comment by grapewheel** [comment]
好的，感谢支持！
