### ISSUE TITLE
这个项目挺好的，请问有讨论群吗

### ISSUE THREAD

**Issue by BruceFeng518** [grapewheel/avvw#15]
这个项目挺好的，请问有讨论群吗

**Comment by grapewheel** [comment]
你好，感谢支持！我们自己有一个it party微信群，专门针对这个项目的群就没有设立

**Comment by BruceFeng518** [comment]
我在apicloud 运行后提示，home.html找不到，是什么原因呢？微信群是你们内部吗

**Comment by grapewheel** [comment]
你需要根据 [README](https://github.com/grapewheel/avvw/blob/master/README.md ) 指引来做，除了打开了wifi服务，还需打开本地编译服务，同时要修改你的本地编译服务局域网IP地址
