### ISSUE TITLE
尽量使用vue

### ISSUE THREAD

**Issue by dong136279559** [grapewheel/avvw#16]

**Comment by dong136279559** [comment]
您好,我想尽量使用vue,路由进行页面跳转,不适用apicloud的api,不知道这样的话会有什么问题,ejs文件是否也没有必要配置了,dev.config 是否也要进行修改呢?不知道这样行不行

**Comment by grapewheel** [comment]
其实是可用vue router的，apicloud的原理是每个页面开一个浏览器框架来运行，而你可以只打开一个win来承载所有页面，但这样的话有可能导致低端机效率较差，并且第一次装载比较慢，其他配置可以不改动，其实就是只使用 home.html

**Comment by dong136279559** [comment]
我能请问您一下apicloud 使用 vue-cli构建的项目时,无法同步到手机上,apicloud的编译工具卡死,请我我应该在哪找一些资料呢,我百度并没有解决我的问题.

**Comment by grapewheel** [comment]
能具体一点说明一下你遇到的问题吗？你是怎么操作的？例如怎么建立项目，怎么同步等，运行指令等

**Comment by dong136279559** [comment]
我是按照 https://xiaoqiang730730.github.io/vue_apicloud/oneweekoneapp.html#与apicloud结合  这个例子来构建的,我发现,他就是将vue项目导入apicloud中,增加了一个config.xml的文件,在. syncignore文件中添加同步忽略的文件,这样运行wifi同步,但是我发现这样会导致apicloud编译工具卡死,并不能进行同步,但是我想使用vuex,路由等功能,所以不清楚该如何进行apicloud与vue的结合了,不知道我的描述您能否看懂?

**Comment by grapewheel** [comment]
哦，我想了解下，你说的apicloud编译工具卡死，是wifi同步时卡死，还是同步完后运行卡死？另外，你使用avvw也可以实现你的vue spa单页面实例架构，这个框架已经经历了落地项目实现，效果不错，你可以尝试下

**Comment by grapewheel** [comment]
另外，如果你是刚入门，也不希望在配置上花太大力气，你可以尝试下 uniapp，但这个混合开发框架做出来的app效率和效果可能比apicloud要差

**Comment by dong136279559** [comment]
是wifi同步时卡死,apicloud编译工具不能进行任何操作了.

**Comment by grapewheel** [comment]
wifi同步时是不是显示上千过万文件在同步？如果是，那么请在 .syncignore加入node_modules的例如，可以参考 [.syncignore](https://github.com/grapewheel/avvw/blob/master/.syncignore)

**Comment by dong136279559** [comment]
嗯嗯,确实是新手入门,好的,avvw确实很好用,我准备使用这个项目进行开发,感谢您对我的帮助.

**Comment by dong136279559** [comment]
您是否有时间修改一下avvw,增加一个可以进行 vue spa单页面实例架构 的模板呢?ejs的配置和webPack的配置,我不太会修改,不知道是否可以呢?

**Comment by grapewheel** [comment]
不用修改的，好像你平时写vue一样，在src里开发代码即可，任何npm模块都可以用，vue router，vuex等，因为apicloud默认先会打开入口页面，avvw默认的入口页面是 home.vue

**Comment by dong136279559** [comment]
嗯嗯,好的,非常感谢您

**Comment by dong136279559** [comment]
您好,我在avvw中使用vant时,标签不能写成<van-button/>,只能使用<Button>且有的属性也无法使用,请问您遇到过这种问题吗?

**Comment by grapewheel** [comment]
什么意思？能具体点上点代码吗？

**Comment by dong136279559** [comment]
import { Button, Icon, Row, Col, Search, List, Cell } from "vant";
在项目中使用的时候,<van-button icon="star-o" type="primary">按钮</van-button>不起作用,只能使用<Button> 标签,而且icon属性设置没有效果(vant版本为2.0.2)

**Comment by dong136279559** [comment]
在vue中调用apicloud的openWin方法时,会有0.5s的黑屏时间,之后下一个vue界面才会展示出来,没有特别顺畅的感觉,请问您有遇到过这种情况吗?感谢您的帮助..谢谢

**Comment by grapewheel** [comment]
> 在vue中调用apicloud的openWin方法时,会有0.5s的黑屏时间,之后下一个vue界面才会展示出来,没有特别顺畅的感觉,请问您有遇到过这种情况吗?感谢您的帮助..谢谢

用wifi同步本地测试时，由于是通过局域网从本地电脑获取页面数据后，再在手机上渲染，如果本地局域网wifi传输慢就会在第一次页面加载时有少量延迟，第二次加载就不会，发布版是不会出现这种情况的

**Comment by grapewheel** [comment]
> ```
> import { Button, Icon, Row, Col, Search, List, Cell } from "vant";
> ```
> 
> 在项目中使用的时候,按钮不起作用,只能使用 标签,而且icon属性设置没有效果(vant版本为2.0.2)

avvw不是使用vant 2.0.2 版本，因为avvw开发时vant还没有推出2.0版本，留意package.json，你要查看vant的旧版本文档或者升级vant
```json
  "dependencies": {
    "@babel/polyfill": "^7.4.0",
    "@babel/runtime": "^7.4.2",
    "vant": "^1.6.11",
    "vue": "^2.6.10"
  }
```

**Comment by dong136279559** [comment]
您好,谢谢您的解答,我现在使用avvw在图片等静态资源的使用上有些问题,图片在vue中设置src无法显示图片,且打包的时候,images文件夹并没有打包进dist文件夹,请问图片使用这,有什么需要注意的地方吗?

**Comment by grapewheel** [comment]
首先images必须放在src目录下，因为webpack打包检索时只会检索src目录，而且需要使用你当前页面相对image目录位置来引用，例如``<image src="../images/xx.jpg"``，那么webpack就能找到你的图片并打包
