### ISSUE TITLE
为什么编译后的每个js文件里都有vue的全部代码？

### ISSUE THREAD

**Issue by zbeol** [grapewheel/avvw#17]
为什么编译后的每个js文件里都有vue的全部代码？
![image](https://user-images.githubusercontent.com/2044702/60637998-43e1fe80-9e4f-11e9-8ae6-1acf560704f8.png)

**Comment by grapewheel** [comment]
因为这个是由apicloud的运作原理决定的，apicloud每个page其实是一个新的小型浏览器实体，那么vue必须被加载才能运行vue代码，不是spa架构
