### ISSUE TITLE
项目中使用vant的tabs出现警告

### ISSUE THREAD

**Issue by dong136279559** [grapewheel/avvw#18]
![EF632328-F691-45CB-AC3C-DD38A0E3397A](https://user-images.githubusercontent.com/20337504/60932946-d15f9b80-a2f2-11e9-8769-564334fa9f67.png)

tab1.vue中使用 Tabs,Tab时,会有警告产生,请问这个是怎么产生的呢?

<template>
	<div>
		<Header :left="true" :mytitle="'我的文件'"/>
		<Tabs v-model="active" class="tabContent">
			<Tab v-for="item,index in dataSource" :title='item' :key="item">
		    内容 {{ item + index}}
				<List v-model="loading" :finished="finished" finished-text="没有更多了" @load="onLoad">
							<Cell v-for="info in list" :key="info" :title="info"/>
				</List>
		  </Tab>
		</Tabs>
	</div>
</template>
<script>
	import Header from "@/components/header.vue";
	import { Tab, Tabs , List ,Cell} from 'vant';
	import apicloud from "@/libs/apicloud";

	window.tab1Vue = {
		name: "tab1",
		components: { Header,Tab, Tabs , List,Cell },
		data() {
			return {
				dataSource: ['全部文件','待我签署','代他人签','已完成','我发起的','纸质文件'],
				active:1,
				list: [],
				loading: false,
				finished: false
			};
		},
		mounted() {
			let navHeight = apicloud.dom("#nav").offsetHeight;
			apicloud.dom(".tabContent").style.cssText="margin-top:"+navHeight+"px;";
		},
		methods: {
			onLoad() {
				// 异步更新数据
				setTimeout(() => {
					for (let i = 0; i < 10; i++) {
						this.list.push(this.list.length + 1);
					}
					// 加载状态结束
					this.loading = false;

					// 数据全部加载完成
					if (this.list.length >= 40) {
						this.finished = true;
					}
				}, 500);
			}
		}
	};

export default window.tab1Vue;
</script>
<style scoped>
</style>

**Comment by dong136279559** [comment]
vant版本在1.6.11的时候没有这些警告,是不是vant版本与vue版本的问题呢

**Comment by grapewheel** [comment]
vant最新版本是支持vue2的，应该是代码有错误而已，我这边测试过框架例子是正常的

**Comment by dong136279559** [comment]
你那使用tabs,也是正常的吗? 没有报警告吗?

**Comment by grapewheel** [comment]
我这边没有发现警告，我看你的警告输出，貌似是Tabs的某些attrs被重复使用了，是不是你的Tab上注册了什么？

**Comment by dong136279559** [comment]
<Tabs v-model="active" class="tabContent" animated lazy-render swipeable >
		<Tab v-for="(item,index) in dataSource" :title='item' :name="index" :key="item">
			测试内容:之后看看展示什么 {{ item + index}}

		</Tab>
	</Tabs>

我是这样写的,放到avvw的demo项目中就出现警告了,您可以试一下这个.这个会产生警告

**Comment by dong136279559** [comment]
是否是vue与vant版本的问题呢,不知道您测试有没有出现警告.

**Comment by xiaosatufu** [comment]
我也出现了同样的问题。。不知道有解决方案了嘛？@dong136279559

**Comment by dong136279559** [comment]
@xiaosatufu 我这没管它,就一直报警告呢,我问了vant官方的人员,他们要codesandbox的地址,单独使用vant的时候确实不报错,不知道咋回事

**Comment by xiaosatufu** [comment]
@dong136279559 谢谢您的回复，最近一个项目用了avvw，其他我都感觉蛮好的，就是有一些vant的组件调用总会有一些问题，也不知道怎么解决TAT，还有使用Popup和Dialog的组件，也会有一些问题，还在慢慢爬坑。。

**Comment by dong136279559** [comment]
我也在爬坑,其他使用起来确实不错,有问题一块交流.

**Comment by grapewheel** [comment]
@dong136279559 @xiaosatufu  请降级使用 vant 1.x，经过测试2.x版本在不使用vue3-cli编译的话会有bug

```js
"dependencies": {
    "@babel/polyfill": "^7.4.4",
    "@babel/runtime": "^7.5.5",
    "vant": "^1.6.24",
    "vue": "^2.6.10"
  }
```
