### ISSUE TITLE
下拉刷新bug

### ISSUE THREAD

**Issue by dong136279559** [grapewheel/avvw#19]
<PullRefresh> + <List> 搭配使用的时候, 下拉只能在展示的cell时下拉才有效果,如果cell只有一个,在空白区域下拉是没有效果的,只能在点击cell的时候下拉,请问这个有没有办法解决一下呢.?

**Comment by grapewheel** [comment]
在使用vant组件下拉或上拉刷新时遇到问题，可以直接使用**apicloud**的下拉或上拉触发事件判断，避免在app中的web组件位移事件触发无效问题
