### ISSUE TITLE
vant 里边的组件,无法使用

### ISSUE THREAD

**Issue by duchao1990** [grapewheel/avvw#20]
![image](https://user-images.githubusercontent.com/9289694/61187462-fc0b7480-a6a3-11e9-9bca-dc24feaf7c63.png)
![image](https://user-images.githubusercontent.com/9289694/61187472-16455280-a6a4-11e9-98c2-f4b0f9c14391.png)
vant版本也是最新的

**Comment by grapewheel** [comment]
请问你是在哪里引入如下语句的？
```
import { Tabbar, TabarItem} from 'vant'
Vue.use(Tabbar).use(TabbarItem)
```

**Comment by duchao1990** [comment]
![image](https://user-images.githubusercontent.com/9289694/61193097-f8034500-a6eb-11e9-9466-828c61e888c8.png)

**Comment by duchao1990** [comment]
van-swipe 我是按照官网调用的

**Comment by duchao1990** [comment]
我也尝试过Swipe 代替 van-swipe是可以使用的,但是有些组件是没法使用的比如 van-image van-col都是无法用的,请问怎么写才能使用

**Comment by duchao1990** [comment]
可以用了,还得Vue.use(Swipe).use(SwipeItem)写这个,我以为components,里边有就可以了吗,熬夜熬晕了

**Comment by grapewheel** [comment]
呵呵，注意休息，不过这里要和你说下：
```js
import {Search} from 'vant';
window.tab1Vue = {
  components {Search}
}
```
> 注意component注册的组件名称是 Search，所以在 <template> 里面也是用 Search，你也可以修改注册名称：
```js
window.tab1Vue = {
  components {'my-search': Search}
}
```
> 这样写的话，在<template>中是 <my-search>，详细请看vue组件使用
