### ISSUE TITLE
如何引入其他cdn？望详细告知，感谢～

### ISSUE THREAD

**Issue by djroad** [grapewheel/avvw#21]
如何使用其他vue 组件 和框架还有其他的开源框架 如何添加，如何引入其他cdn？望详细告知，感谢～

**Comment by grapewheel** [comment]
请先深入了解下vue的组件引入，使用和vue一样，只是apicloud的每个页面一个浏览器初始化一个vue实体，而web端vue是一个浏览器只初始化一个vue实体而已
