### ISSUE TITLE
有QQ群或者微信群吗?

### ISSUE THREAD

**Issue by xiaosatufu** [grapewheel/avvw#26]
请问有微信群或者QQ群可以加入以下吗？

**Comment by grapewheel** [comment]
你好，由于本人没有太多时间一一回答各位技术问题，所以暂不建群

**Comment by xiaosatufu** [comment]
不是回答问题，是觉得这个项目挺好的。大家沟通交流一下也是挺好的呀。

**Comment by grapewheel** [comment]
感谢您的支持！明天我开一个微信群加一起吧

**Comment by grapewheel** [comment]
@xiaosatufu 已开QQ群 492968709，不经常登录QQ，如需加群请留言
