### ISSUE TITLE
popup组件问题

### ISSUE THREAD

**Issue by xiaosatufu** [grapewheel/avvw#28]
直接调用popup组件会出现
[Vue warn]: Error in nextTick: "TypeError: Cannot set property 'zIndex' of undefined"
vue.js:1841 TypeError: Cannot set property 'zIndex' of undefined
不知道有没有解决方案。

**Comment by grapewheel** [comment]
请问您使用的vant版本是多少？或者贴一下代码

**Comment by xiaosatufu** [comment]
1，clone本项目
2，cnpm i
3，
![image](https://user-images.githubusercontent.com/12179854/62548238-11398480-b899-11e9-8626-a1200a3bf673.png)
4，npm run dev

![image](https://user-images.githubusercontent.com/12179854/62548287-23b3be00-b899-11e9-91bb-45bc607f3aac.png)
版本
![image](https://user-images.githubusercontent.com/12179854/62548324-30381680-b899-11e9-8a90-27a57f7e1c79.png)

**Comment by grapewheel** [comment]
@xiaosatufu  请降级使用 vant 1.x，经过测试2.x版本在不使用vue3-cli编译的话会有bug

```js
"dependencies": {
    "@babel/polyfill": "^7.4.4",
    "@babel/runtime": "^7.5.5",
    "vant": "^1.6.24",
    "vue": "^2.6.10"
  }
```
