### ISSUE TITLE
如何真机调试？

### ISSUE THREAD

**Issue by goldencolor** [grapewheel/avvw#3]
按照说明 步骤都走完，并且自定义loader也链接到wifi，但是一直没有更新代码。。

**Comment by grapewheel** [comment]
@goldencolor 
你是否有在根目录下运行 npm run wifi-sync？这个命令会先将代码编译，然后再同步到手机上，同步时app loader必须处于激活状态

**Comment by grapewheel** [comment]
再次强调

**还有一点特别注意 config.xml 中** 
`<widget id="A6987304680XXX" version="0.0.1">`
**的 widget id必须和你的自定义loader的项目ID一样才能同步！！**

**Comment by goldencolor** [comment]
已解决，但有些细节还是觉得有问题，比如引入api.css默认所有页面都引入以及脚手架升级到vue3.0之类的

**Comment by grapewheel** [comment]
@goldencolor 建议不要在模板页面引入api.css，因为api.css是apicloud提供的页面基准样式，而框架植入的vant UI和其他的vue前端已经有类似的基准样式，所以无需引入api.css，而且要引入，也建议用import css 方式，而不是模板页面直接引入

**Comment by grapewheel** [comment]
@goldencolor 因为很多前端框架还没有兼容升级vue3.0，所以暂时没有使用vue3
