### ISSUE TITLE
关于组件调用$attrs is readonly. $listeners is readonly.

### ISSUE THREAD

**Issue by xiaosatufu** [grapewheel/avvw#30]
使用组件的时候，总是会出现这些错误，但是不影响使用。想知道这些错误是怎么出来的，应该怎么解决呢？
现在使用的DatePicker组件，tab组件，DropdownMenu, DropdownItem组件等，都会出现这个问题。
引入方式
![image](https://user-images.githubusercontent.com/12179854/62605134-0ed43a80-b92c-11e9-9bad-4847a00cc4d5.png)
![image](https://user-images.githubusercontent.com/12179854/62605151-1562b200-b92c-11e9-915a-c5778ac6d23f.png)

![image](https://user-images.githubusercontent.com/12179854/62605112-04b23c00-b92c-11e9-9f86-85b76cd0e0ad.png)

**Comment by grapewheel** [comment]
@xiaosatufu  请降级使用 vant 1.x，经过测试2.x版本在不使用vue3-cli编译的话会有bug

```js
"dependencies": {
    "@babel/polyfill": "^7.4.4",
    "@babel/runtime": "^7.5.5",
    "vant": "^1.6.24",
    "vue": "^2.6.10"
  }
```
