### ISSUE TITLE
请问 如何给全局引入一个样式

### ISSUE THREAD

**Issue by wjy397** [grapewheel/avvw#35]
我做页面的时候  body浏览器默认样式是margin:8px   想去掉这个默认样式，在index.html的head头里加了reset.css没有用 请问 如何解决这个问题？

**Comment by grapewheel** [comment]
是没有用的，因为index.html 只是用以打开入口页面：
```js
apiready = function () {
    api.openFrame({
      name: 'home',
      url: url,
      rect: {
        x: 0,
        y: 0,
        w: api.winWidth,
        h: api.winHeight
      }
    })
  }
```
您可以尝试在 [page.ejs](https://github.com/grapewheel/avvw/blob/master/src/templates/page.ejs) 上添加

**Comment by wjy397** [comment]
谢谢
