### ISSUE TITLE
关于头部传参的问题

### ISSUE THREAD

**Issue by wjy397** [grapewheel/avvw#36]
home.vue自定义了一个header组件，头部组件可以动态显示当前页面名称，请问，头部下面的页面都是openFrameGroup打开的，怎么动态控制头部组件在不同页面动态显示不同的名称？

**Comment by grapewheel** [comment]
header组件是vue组件，可以随意import任意页面，或者不import，无需将内容部分用openWin等重新打开一个区域，这样对维护上非常不便，也无必要
