### ISSUE TITLE
打包后的widget上传后怎么生效的

### ISSUE THREAD

**Issue by moqin** [grapewheel/avvw#39]
把打包后的widget上传到代码那边了，但是编译后还是以前的，并不是打包后的，这个要怎么处理的

**Comment by grapewheel** [comment]
最新版编译上传
```bash 
npm run build # 编译
```
编译后，修改./dist 目录名称为 ./widget，压缩./widget 文件夹生成 widget.zip 上传 apicloud 后台的“代码”处即可进行发布

**Comment by moqin** [comment]
最新版的，我使用例子打包
css/
js/
config.xml
home.html
index.html
tabs-tab1.html
....
这样的结构是可以的？
看到apicloud的结构好像是有html/的

**Comment by grapewheel** [comment]
widget中的结构不会影响app运行，只需相互之间能找到对方即可
