### ISSUE TITLE
不支持es6语法问题

### ISSUE THREAD

**Issue by PrintingChen** [grapewheel/avvw#5]
![image](https://user-images.githubusercontent.com/17898144/52529339-df50c680-2d2a-11e9-8cab-98ce69154567.png)

不支持es6语法，如何支持呢？

**Comment by PrintingChen** [comment]
第一个框的语法不支持，第二个框的语法才支持，如何支持呢？

**Comment by grapewheel** [comment]
@PrintingChen 
对的，page.ejs的模板为了兼容低端机是不支持es6语法，要修改一下，已更新，感谢提出！
