### ISSUE TITLE
ejs生成的页面会引入多个当前页面看起来不需要的script和style文件

### ISSUE THREAD

**Issue by Viarotel** [grapewheel/avvw#8]
1. 所有页面都引入的 script 对应了page文件夹的文件名 即使有些看上去并不需要
2,引入的style文件是重复的
3. 是否会影响性能

**Comment by Viarotel** [comment]
> 1. 所有页面都引入的 script 对应了page文件夹的文件名 即使有些看上去并不需要
> 2,引入的style文件是重复的
> 3. 是否会影响性能

**Comment by Viarotel** [comment]
>  所有页面都引入的 script 对应了page文件夹的文件名 即使有些看上去并不需要
>  引入的style文件是重复的
>  是否会影响性能

**Comment by Viarotel** [comment]
> 1. 所有页面都引入的 script 对应了page文件夹的文件名 即使有些看上去并不需要
>    2,引入的style文件是重复的
> 2. 是否会影响性能

**Comment by grapewheel** [comment]
的确有这个问题，我会修改webpack支持单独组件导入，谢谢你提醒

**Comment by grapewheel** [comment]
@Viarotel 已修正更新，只需更新以下四个文件即可，非常感谢您的反馈！
`./src/templates/page.ejs
./webpack.base.js
./webpack.dev.js
./webpack.prod.js
`

**Comment by Viarotel** [comment]
不用客气, 脚手架很好用

**Comment by grapewheel** [comment]
使用过程中有什么问题和改进可以随时提出来，再次感谢！
