### ISSUE TITLE
最新版本无法访问

### ISSUE THREAD

**Issue by Viarotel** [grapewheel/avvw#9]
C:\Users\Administrator\Desktop\avvw\avvw-master\avvw>npm run dev

> avvw@1.1.0 dev C:\Users\Administrator\Desktop\avvw\avvw-master\avvw
> webpack-dev-server --open --config webpack.dev.js

i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wdm｣: wait until bundle finished: /

#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 000000CF278FDA50npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! avvw@1.1.0 dev: `webpack-dev-server --open --config webpack.dev.js`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the avvw@1.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-04-29T06_35_32_769Z-debug.log

**Comment by grapewheel** [comment]
请问有 npm i 先安装依赖吗？
我这边测试是可以的，npm run dev 是网页浏览调试，npm run wifi-dev 是真机wifi同步
```
npm i

npm run wifi-start # 开wifi服务，wifi-stop 停止服务   
npm run wifi-dev # 真机wifi无压缩同步，速度快
npm run wifi-build # 真机wifi压缩同步，速度慢
npm run wifi-log # 真机wifi日志输出

npm run support # 测试兼容机型
npm run dev # 开启本地测试   

npm run build # 编译
```

**Comment by Viarotel** [comment]
是的, npm install 过了

**Comment by grapewheel** [comment]
是整个项目 git clone 下来重新编译测试吗？我这边是正常的
![深度截图_选择区域_20190429152418](https://user-images.githubusercontent.com/490426/56881400-def6da80-6a92-11e9-91cf-25c5aad73713.png)
![深度截图_选择区域_20190429152333](https://user-images.githubusercontent.com/490426/56881401-df8f7100-6a92-11e9-8961-52a57ea63957.png)

**Comment by grapewheel** [comment]
@Viarotel 你打开  C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-04-29T06_35_32_769Z-debug.log 这个 log 看看错误输出，可能是你的npm版本或者node版本过低问题

**Comment by Viarotel** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.0.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle avvw@1.1.0~predev: avvw@1.1.0
6 info lifecycle avvw@1.1.0~dev: avvw@1.1.0
7 verbose lifecycle avvw@1.1.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle avvw@1.1.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Administrator\Desktop\avvw\avvw-master\avvw\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\phpStudy\php55;D:\phpStudy\php55\ext;D:\phpStudy\MySQL\bin;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\TortoiseGit\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Administrator\.windows-build-tools\python27;C:\Users\Administrator\AppData\Local\Temp\yarn--1556265613217-0.29284419005091955;C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\windows-build-tools\node_modules\.bin;C:\Users\Administrator\AppData\Local\Yarn\Data\link\node_modules\.bin;C:\Program Files\libexec\lib\node_modules\npm\bin\node-gyp-bin;C:\Program Files\lib\node_modules\npm\bin\node-gyp-bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\phpStudy\php55;D:\phpStudy\php55\ext;D:\phpStudy\MySQL\bin;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\TortoiseGit\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;;D:\Microsoft VS Code\bin;C:\Program Files\Bandizip\;C:\Users\Administrator\AppData\Local\Yarn\bin;C:\Users\Administrator\AppData\Local\Programs\Fiddler;C:\Users\Administrator\AppData\Roaming\npm
9 verbose lifecycle avvw@1.1.0~dev: CWD: C:\Users\Administrator\Desktop\avvw\avvw-master\avvw
10 silly lifecycle avvw@1.1.0~dev: Args: [ '/d /s /c', 'webpack-dev-server --open --config webpack.dev.js' ]
11 silly lifecycle avvw@1.1.0~dev: Returned: code: 3221225477  signal: null
12 info lifecycle avvw@1.1.0~dev: Failed to exec dev script
13 verbose stack Error: avvw@1.1.0 dev: `webpack-dev-server --open --config webpack.dev.js`
13 verbose stack Exit status 3221225477
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:196:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:196:13)
13 verbose stack     at maybeClose (internal/child_process.js:1000:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)
14 verbose pkgid avvw@1.1.0
15 verbose cwd C:\Users\Administrator\Desktop\avvw\avvw-master\avvw
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v12.0.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 3221225477
22 error avvw@1.1.0 dev: `webpack-dev-server --open --config webpack.dev.js`
22 error Exit status 3221225477
23 error Failed at the avvw@1.1.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3221225477, true ]

**Comment by Viarotel** [comment]
C:\Users\Administrator\Desktop\avvw\avvw-master\avvw>npm -v
6.9.0

C:\Users\Administrator\Desktop\avvw\avvw-master\avvw>node -v
v12.0.0

**Comment by grapewheel** [comment]
试下用 node v10.15.0 版本，不要用v12.0.0 版本，v10.15.0 LTS 是长期支持版本，v12.0.0是超前版本，某些模块还没有支持太新特性

![深度截图_选择区域_20190429162002](https://user-images.githubusercontent.com/490426/56883919-b4108480-6a9a-11e9-873c-620e262f7640.png)

**Comment by Viarotel** [comment]
好的,我回退试试看,麻烦了

**Comment by Viarotel** [comment]
node降级后 问题解决了, 多谢您的帮助

**Comment by grapewheel** [comment]
恩， [node12特性](https://mp.weixin.qq.com/s?__biz=MzAwNjI5MTYyMw==&mid=2651497342&idx=1&sn=c113b10d1de84e57a2d6c6bf9a917256&chksm=80f1aab6b78623a00f689df82a40cd182cfd2758beed8b42d845187f5444145a7bd1e56aa096&mpshare=1&scene=1&srcid=#rd) 你可以看看
